version: '3.8'

services:
  application-web-service:
    container_name: application-web-service
    build:
      context: docker/nginx
      args:
        UID: $U_ID
    ports:
      - 1100:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - application-service-backend
    networks:
      - parking-microservices-network

  application-service-backend:
    container_name: application-service-backend
    build:
      context: docker/php
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    env_file:
      - .env
    depends_on:
      - application-service-db
    networks:
      - parking-microservices-network

  application-service-db:
    container_name: application-service-db
    build:
      context: ./docker/database
    ports:
      - 10100:3306
    environment:
      MYSQL_DATABASE: application_database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - application-service-db-data:/var/lib/mysql
    networks:
      - parking-microservices-network
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  application-service-db-data:

networks:
  parking-microservices-network:
    external: true
