version: '3.8'

services:
  application-web-service:
    container_name: application-web-service
    build:
      context: docker/nginx
      args:
        UID: $U_ID
    ports:
      - 1100:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - application-service-backend
    networks:
      - parking-microservices-network

  application-service-backend:
    container_name: application-service-backend
    build:
      context: docker/php
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    env_file:
      - .env
    depends_on:
      - application-service-db
    networks:
      - parking-microservices-network

  application-service-db:
    container_name: codenip-ms-application-service-db
    build:
      context: ./docker/database
    ports:
      - 10100:3306
    environment:
      MYSQL_DATABASE: application_database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - application-service-db-data:/var/lib/mysql
    networks:
      - parking-microservices-network
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

volumes:
  application-service-db-data:

networks:
  parking-microservices-network:
    external: true
