parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\Messenger\Handler\UserRegisteredMessageHandler:
        tags: [ 'messenger.message_handler' ]
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


